id: P006750
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC448
  title: ཁུང་ཙིའི་གསུང་སྒྲོས།
  author: ''
  volumes:
    b5a8d58bcf064061b9e38d5951836a1e:
      image_group_id: I2PD18372
      title: ''
      volume_number: 1
      total_pages: 370
      base_file: v001.txt
